spring.application.name=Ventas (dev)

#Driver usar para conectarse a la BD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Define cómo conectarse a la base de datos
#spring.datasource.url=jdbc:oracle:thin:@TNS_NAME?TNS_ADMIN=D:/...
#spring.datasource.url=jdbc:oracle:thin:@bdejemplofiestas_high?TNS_ADMIN=D:/Fullstack1/Wallet/
spring.datasource.url=jdbc:oracle:thin:@bdejemplofiestas_high?TNS_ADMIN=/Users/arkder/Desktop/Aplicaciones/FullStack1/2026_1_FullStack1_EjemploTrabajoSemestral/Wallet/

#Usuario BD
spring.datasource.username=ADMIN

#Pass BD
spring.datasource.password=Duoc.2026Fiestas

#Estrategia de creación de tablas (none, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=none

#Muestra en consola las consultas SQL que ejecuta Hibernate
spring.jpa.show-sql=true

#Formatear SQL consola
spring.jpa.properties.hibernate.format_sql=true

#Dialecto de Hibernate, le dice como generar el SQL para Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

#Indica el puerto que usara el microservicio
server.port=8081