spring.application.name=FIESTA-SERVICE

#Driver usar para conectarse a la BD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Define cómo conectarse a la base de datos
#spring.datasource.url=jdbc:oracle:thin:@TNS_NAME?TNS_ADMIN=D:/...
spring.datasource.url=jdbc:oracle:thin:@bdejemplofiestas_high?TNS_ADMIN=D:/Fullstack1/2026_1_FullStack1_MicroServicioFiesta/Wallet/
#spring.datasource.url=jdbc:oracle:thin:@bdejemplofiestas_high?TNS_ADMIN=/Users/arkder/Desktop/Temporal/2026_1_FullStack1_MicroServicioFiesta/Wallet/

#Usuario BD
spring.datasource.username=ADMIN

#Pass BD
spring.datasource.password=Duoc.2026Fiestas

#Estrategia de creación de tablas (none, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=none

#Muestra en consola las consultas SQL que ejecuta Hibernate
spring.jpa.show-sql=true

#Formatear SQL consola
spring.jpa.properties.hibernate.format_sql=true

#Dialecto de Hibernate, le dice como generar el SQL para Oracle
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

#Indica el puerto que usara el microservicio
server.port=8081

jwt.secret=clave-super-secreta-para-clase-123456


# Para habilitar configuración con swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.enable-hateoas=false

# URL donde está publicado Eureka Server.
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
 
# true = este microservicio se registra en Eureka al iniciar.
eureka.client.register-with-eureka=true
 
# true = permite consultar el registro de servicios.
# En Auth no es estrictamente necesario si no llama a otros servicios,
# pero se deja true para mantener una configuración simple y homogénea.
eureka.client.fetch-registry=true
 
# Publica preferentemente la IP del servicio en vez del hostname.
eureka.instance.prefer-ip-address=true